server:
  port: 8092
spring:
  application:
    name: mvsc-apartments
  config:
    import: optional:configserver:http//localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/apartments_ms
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
eureka: 
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka    