server:
  port: 8090
spring:
  application:
    name: mvsc-users
  config:
    import: optional:configserver:http//localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/usersDB
    username: root
    password: Motica2002@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

eureka: 
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka