server:
  port: 8091
spring:
  application:
    name: microservice-residents
  config:
    import: optional:configserver:http//localhost:8888
  datasource:
    url: jdbc:sqlite:mydatabase.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create

eureka: 
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka